### ISSUE TITLE
595. Big Countries

### ISSUE THREAD

**Issue by alpanasinha** [alpanasinha/Leetcode-Problems#28]

**Comment by asmitraj05** [comment]
Can i take this? @alpanasinha

**Comment by alpanasinha** [comment]
Sure! Thanks for taking interest in this repository! @asmitraj05

**Comment by jatin140820** [comment]
can i use sql for this

**Comment by alpanasinha** [comment]
@jatin140820 Yes, Please read the contribution.MD file for clarification

**Comment by jatin140820** [comment]
can i take this up?
